# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mvndrawC <- function(mu, sig) {
    .Call('_fatBVARS_mvndrawC', PACKAGE = 'fatBVARS', mu, sig)
}

carterkohn <- function(y, Z, Ht, Qt, m, p, t, B0, V0) {
    .Call('_fatBVARS_carterkohn', PACKAGE = 'fatBVARS', y, Z, Ht, Qt, m, p, t, B0, V0)
}

alphahelper <- function(y, Z, Btdraw) {
    .Call('_fatBVARS_alphahelper', PACKAGE = 'fatBVARS', y, Z, Btdraw)
}

sigmahelper1 <- function(Atdraw, M) {
    .Call('_fatBVARS_sigmahelper1', PACKAGE = 'fatBVARS', Atdraw, M)
}

sigmahelper2 <- function(capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_fatBVARS_sigmahelper2', PACKAGE = 'fatBVARS', capAt, yhat, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

#' @export
sigmahelper4 <- function(y2, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar) {
    .Call('_fatBVARS_sigmahelper4', PACKAGE = 'fatBVARS', y2, qs, ms, u2s, Sigtdraw, Zs, Wdraw, sigma_prmean, sigma_prvar)
}

sigmahelper3 <- function(capAt, sigt) {
    .Call('_fatBVARS_sigmahelper3', PACKAGE = 'fatBVARS', capAt, sigt)
}

getvc <- function(Ht) {
    .Call('_fatBVARS_getvc', PACKAGE = 'fatBVARS', Ht)
}

makeregs_fcC <- function(ydat, p) {
    .Call('_fatBVARS_makeregs_fcC', PACKAGE = 'fatBVARS', ydat, p)
}

mz <- function(n) {
    .Call('_fatBVARS_mz', PACKAGE = 'fatBVARS', n)
}

meye <- function(n) {
    .Call('_fatBVARS_meye', PACKAGE = 'fatBVARS', n)
}

vechC <- function(x) {
    .Call('_fatBVARS_vechC', PACKAGE = 'fatBVARS', x)
}

getfcsts <- function(Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p) {
    .Call('_fatBVARS_getfcsts', PACKAGE = 'fatBVARS', Bt0, At0, Sigt0, Qdraw, Sdraw, Wdraw, ydat, nf, p)
}

wishdrawC <- function(h, n) {
    .Call('_fatBVARS_wishdrawC', PACKAGE = 'fatBVARS', h, n)
}

makeregs2_fcC <- function(dat, p) {
    .Call('_fatBVARS_makeregs2_fcC', PACKAGE = 'fatBVARS', dat, p)
}

matmult <- function(x, nt) {
    .Call('_fatBVARS_matmult', PACKAGE = 'fatBVARS', x, nt)
}

varfcst <- function(b, sig, y, nf) {
    .Call('_fatBVARS_varfcst', PACKAGE = 'fatBVARS', b, sig, y, nf)
}

